### PR TITLE
added alpha fold link to tf function page and few bug fixes

### LINKED ISSUE #183: Add AlphaFold links to set of TFs with data

### LINKED ISSUE #186: Function page breaks phospho Transcription factors
https://factorbook2-0.vercel.app/tf/human/POLR2AphosphoS5/function breaks

### PR DESCRIPTION
**Pull request by NishiPhalke**
Fixes #186 
Fixes #183 

Also, Corrects LinkWrapper Component to route to TF Details page from All TFs/Celltypes tables.

### CODE REVIEW

**Comment by jpfisher72** [comment]
What is the expected behavior of this tab:
https://factorbook2-0-git-alphafold-screenumass-projects.vercel.app/tf/human/POLR2AphosphoS5/geneexpression

Currently it's an infinite skeleton

File: src/app/tf/[species]/[factor]/function/function.tsx [hunk 1]
```diff
@@ -62,7 +63,7 @@ const FunctionTab: React.FC<FunctionPageProps> = (props) => {
     loading: factorLoading,
     error: factorError,
   } = useQuery<FactorQueryResponse>(FACTOR_DESCRIPTION_QUERY, {
-    variables: { assembly: props.assembly, name: [props.factor] },
+    variables: { assembly: props.assembly, name: [props.factor.split(/phospho/i)[0]] },
```
Comment (jpfisher72) [inline src/app/tf/[species]/[factor]/function/function.tsx:66]: Are there any other TFs with variants like POLR2AphosphoS5?

**Review by jpfisher72 — APPROVED** [review]

File: src/app/tf/[species]/[factor]/function/function.tsx (hunk 1 above)
Comment (NishiPhalke) [reply src/app/tf/[species]/[factor]/function/function.tsx:66]: I know of only phospho TF variants

**Comment by NishiPhalke** [comment]
> What is the expected behavior of this tab: https://factorbook2-0-git-alphafold-screenumass-projects.vercel.app/tf/human/POLR2AphosphoS5/geneexpression
> 
> Currently it's an infinite skeleton
> 
> edit: Maybe need to remove the "phosphoS5" from POLR2AphosphoS5?

Fixed this

**Comment by NishiPhalke** [comment]
> What is the expected behavior of this tab: https://factorbook2-0-git-alphafold-screenumass-projects.vercel.app/tf/human/POLR2AphosphoS5/geneexpression
> 
> Currently it's an infinite skeleton
> 
> edit: Maybe need to remove the "phosphoS5" from POLR2AphosphoS5?

Fixed this
